### ISSUE TITLE
Unable to install collection

### ISSUE THREAD

**Issue by MaHusch** [cdot65/pan-scm-ansible#46]
# Versions

#### Ansible
```
ansible [core 2.18.4]
  config file = None
  configured module search path = ['/home/huschi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/huschi/ansible/paloalto-scm/ansible-venv/lib/python3.13/site-packages/ansible
  ansible collection location = /home/huschi/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/huschi/ansible/paloalto-scm/ansible-venv/bin/ansible
  python version = 3.13.3 (main, Apr  9 2025, 08:55:03) [GCC 9.4.0] (/home/huschi/ansible/paloalto-scm/ansible-venv/bin/python3.13)
  jinja version = 3.1.6
  libyaml = True
```
#### Python

```
Python 3.13.3
```

# Description
Hello everyone,

First of all, please excuse me if I'm not following any best practices for issue creation, this is the first time I'm creating an issue.

Unfortunately I can't manage to install the ansible collection properly. When I try to install the collection using the command `ansible-galaxy collection install cdot65.scm`, I get the following error message: 

```shell
huschi@expedition-server:~/ansible/paloalto-scm$ ansible-galaxy collection install cdot65.scm
Starting galaxy collection install process
Process install dependency map
ERROR! Failed to resolve the requested dependencies map. Could not satisfy the following requirements:
* cdot65.scm:* (direct request)

```
Since this did not work, I cloned the repository and built the collection manually - as shown in the README.
However, I now get an error when I try to run a task. I use the example from the README:

```yaml
- name: Create an IP-based address object
  cdot65.scm.address:
    provider:
      client_id: "{{ client_id }}"
      client_secret: "{{ client_secret }}"
      tsg_id: "{{ tsg_id }}"
    name: "ANSIBLE-TEST"
    folder: "ALL"
    description: "Greetings from Ansible"
    ip_netmask: "1.1.1.1/32"
    state: present
```

I now get the following error message:

`ERROR! plugin redirect loop resolving cdot65.scm.address (path: ['cdot65.scm.address'])`

Am I doing something wrong here?

Best regards,
Martin
