### ISSUE TITLE
Unable to create service object

### ISSUE THREAD

**Issue by MaHusch** [cdot65/pan-scm-ansible#47]
# Versions
## Ansible

```bash
> ansible --version
ansible [core 2.18.4]
  config file = None
  configured module search path = ['/Users/huschi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/huschi/Ansible-Stuff/ansible/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/huschi/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/huschi/Ansible-Stuff/ansible/bin/ansible
  python version = 3.13.2 (main, Feb  4 2025, 14:51:09) [Clang 16.0.0 (clang-1600.0.26.6)] (/Users/huschi/Ansible-Stuff/ansible/bin/python3.13)
  jinja version = 3.1.6
  libyaml = True
```

## Python

```bash
> python --version                
Python 3.13.2
```

# Description

Hi there,

I am unable to create a service object without the `override` option.

I try to create a simple serivce object like this:

```yaml
    - name: SCM - Create TCP service object
      cdot65.scm.service:
        provider: "{{ scm_provider }}"
        name: "Test-01"
        folder: "All"
        protocol:
          tcp:
            port: "8081"
        description: "greetings from ansible"
        state: present
```

Running this Task gives me the following error message from ansible:
```
"msg": "Invalid service data: ['\"protocol.tcp.override\" must be of type object'] - HTTP error: 400 - API error: API_I00035"
```

I also get the same error message when using the examples provided in the [documentation](https://cdot65.github.io/pan-scm-ansible/collection/modules/service/#deleting-services)

But when I try to create the service object with the `pan-scm-sdk` python module, I can easily create an service object. Following code is working for me:

```python
from scm.client import Scm

api_client = Scm (client_id, client_secret, tsg_id)

tcp_data = {
            "name": "API-TEST",
            "protocol": {
                "tcp": {
                    "port": "8081,
                }
            },
            "description": "API Test",
            "folder": "All",
        }

api_client.service.create(tcp_data)

```

As you can see, there is no option for the `override` in the python script. So I do not understand why the ansible module is requiring the option to be set.

FYI: I am using my "workaround" described in #46 

Thank you and best regards,
Martin
